version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devcamp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - devcamp-example-backend

volumes:
  postgres_data:
    driver: local

networks:
  devcamp-example-backend:
    external: true
